
local a = ControlUI.New()
print(ControlUI)
print(ControlUI.GetClassName())
a:SetName("你好 ControlUI")
print(a:GetName())
print(a:IsClass("你好"))
local b = ControlUI.New()
b:SetName("2222")
print(a == b)
a:Delete()
print(a:isnil())
local a = b
print(a:GetInterface("Control"))
a:SetName("aaaaa啊")
print(a:GetName())
print(ButtonUI)
local btn = ButtonUI.New()
btn:SetName("Btn")
print(btn)
print(btn:GetName(),"aaaaaaaaaaaaaaaaaa")
print(btn:isnil())
btn:SetTagCtrl(a)
print(btn:GetTagCtrl())

local list = ListUI.New()
print(list)
print(list:GetClass())
print(list:GetScrollSelect())
print(list == btn)
print(PaintManagerUI.GetInstancePath())
local h,s,l = 0,0,0
h,s,l = PaintManagerUI.GetHSL(h,s,l);
print(h,s,l)
print(PaintManagerUI.GetInstance())
local pa = PaintManagerUI.New()
print(pa,pa:isnil())
print(LuaWindow)
print(WindowWnd)
local win = LuaWindow.New("AAA","main")
print(win,win:isnil())
win:Create(nil,"TestDemo",282001408,393216,0,0,600,320)
win:ShowWindow()
print(NotifyUI)
